config/routes.rb
Rails.application.routes.draw do

  resources :wikis do 
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :sessions 
  resources :users do
    member do 
      get :confirm_email
    end 
  end

  get 'about' => 'welcome#about'
  get 'downgrade' => 'users#downgrade'

  root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :skip_confirmation
  has_secure_password
  has_many :wikis

  has_many :collaborators
  has_many :collab_wikis, source: :wiki, through: :collaborators

  validates :email, uniqueness: true

  before_create :confirmation_token, unless: :skip_confirmation
  after_create :deliver_welcome_email, unless: :skip_confirmation
  after_initialize :default_role

  def admin?
    role == 'admin'
  end

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def skip_confirmation!
    self.skip_confirmation = true
  end

  private

  def confirmation_token
    self.confirm_token = SecureRandom.urlsafe_base64.to_s
  end

  def default_role
    self.role = 'standard' if self.role.blank?
  end

  def deliver_welcome_email
    UserMailer.registration_confirmation(self).deliver_now
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  extend FriendlyId
  friendly_id :title, :use => :slugged 

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  private

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "Blocipedia Premium Membership - #{current_user.name}",
      amount: 15_00
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 15_00,
      description: "Blocipedia Premium Membership - #{current_user.email}",
      currency: 'usd'
      )

    current_user.update_attribute(:role, 'premium')

    flash[:notice] = "Thank you for upgrading your account, #{current_user.email}!"
    redirect_to root_path

  rescue Stripe::CardError => e 
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  # before_action :get_wiki

  def new
    @wiki = Wiki.find(params[:id])
    @collaborator = Collaborator.new
    authorize @collaborator
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.build(collaborator_params)
    @collaborators = User.all 
    @new_collaborator = Collaborator.new

    # authorize @collaborator 

    if @collaborator.save 
      flash[:notice] = "Collaborator has been added successfully."
    else
      flash[:error] = "There was an error. Please try again."
    end

    respond_to do |format| 
      format.html
      format.js
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.find(params[:id])

    # authorize @collaborator
    
    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed successfully."
    else
      flash[:error] = "There was an error. Please try again."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private 

  # def get_wiki 
  #   @wiki = Wiki.find(params[:wiki_id]) 
  # end

  def collaborator_params
    params.require(:collaborator).permit(:wiki_id, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      redirect_to root_path, notice: "Logged in!"
    else
      flash[:error] = "Invalid email or password. Please try again."
      render :new
    end
  end

  def destroy
  session[:user_id] = nil
  redirect_to root_path, notice: "Logged out!"
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = "Please confirm your email address to continue."
      redirect_to root_path
    else
      flash[:error] = "Something went wrong. Please try again."
      render :new
    end
  end

  def confirm_email
    # Find the user by confirmation_token
    @user = User.find_by_confirm_token(params[:id])
    @user.confirmation_token = nil
    @user.confirmed_at = Time.now

    if @user.save
      flash[:notice] = "Account confirmed. Please sign in to continue."
    else
      flash[:error] = "Please confirm your account."
    end
    redirect_to root_path
  end

  def update
    puts "*"*80
    puts session[:user_id]
    puts "*"*80

    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated successfully."
    else
      flash[:notice] = "Invalid user information"
    end
    redirect_to edit_user_path
  end

  def downgrade
    if current_user.update_attribute(:role, 'standard')
      flash[:notice] = "Your account has been downgraded."
    else
      flash[:error] = "There was an error. Please try again."
    end
    current_user.wikis.each do |wiki|
      wiki.update_attribute(:public, true)
    end
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki).paginate(page: params[:page], per_page: 10)
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki 
  end

  def new
    @wiki = Wiki.new 
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)
    if current_user.standard? 
     @wiki.public = true
    else
     @wiki.public = @wiki.public || false 
    end 
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @wiki 
    else
      flash[:error] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    @users = User.all 
    authorize @wiki
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki 
    else
      flash[:error] = "There was an error. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting the wiki. Please try again."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
 <div class="container">
  <% unless current_user.premium? %>
   <%= form_tag charges_path do %>
     <h2>Click the button to upgrade your account to Premium.</h2>
     <h4>With a premium account, you can create your very own private Wiki Pages. This will give you the advantage of sharing internal documents with your team. Keep your Training Wikis private.</h4>
     <br>
     <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
   <% end %>
   <% else %>
   <h3>Click here to downgrade your account. Please be reminded that your Private Wikis will become Public.</h3>
   <%= link_to "Yes, please downgrade my account", downgrade_path, class: 'btn btn-warning' %>
  <% end %>
</div> 

app/views/collaborators/_collaborator.html.erb
<table class="table table-striped">
  <% @wiki.collaborators.each do |collaborator| %>
  <tr id="collaborator-<%= collaborator.id %>">
      <% user = User.find(collaborator.user_id) %>
      <td><%= user.name %></td>
      <td>
      <% if @wiki.user_id == current_user.id || current_user.admin? %>
      <td>
      <%= link_to "Remove Collaborator", [@wiki, collaborator], method: :delete, class: 'btn btn-xs btn-danger', remote: true  %>
      </td>
      <% end %>
    </tr>
  <% end %>
</table> 

app/views/collaborators/_users.html.erb
<table class="table table-striped">
  <% User.all.each do |user| %>
  <% if !@wiki.collaborators.pluck(:user_id).include?(user.id) && !(@wiki.user_id == user.id) %>
    <%= form_for [@wiki, @wiki.collaborators.build], remote: true do |f| %>
      <tr id='user-<%=user.id%>' >
        <tr id='@wiki-<%=@wiki.id%>' >
        <td><%= user.name %></td>
        <td>
          <%= f.hidden_field :user_id, :value => user.id %>
          <%= f.submit 'Add', class: 'btn btn-xs btn-success', method: :create %>   
        <% end %>  
        </td>
      </tr>
      </tr>
    <% end %> 
  <% end %>
</table> 

app/views/collaborators/create.js.erb
 <% if @collaborator.valid? %>
  $('#user-' +<%= @collaborator.user_id %>).hide();
  $('.js-collaborators').html("<%= escape_javascript(render partial: 'collaborators/collaborator') %>").reset();
<% else %>
  $('.new-collaborator').html("<%= escape_javascript(render partial: 'collaborators/users') %>").reset();
<% end %>

app/views/collaborators/destroy.js.erb
<% if @collaborator.destroyed? %>
  $('#collaborator-' +<%= @collaborator.id %>).hide();
<% else %>
  $('#collaborator-' +<%=@collaborator.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %>");
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-pills">
      <li class="active"><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
          Hello <strong><%= link_to (current_user.name || current_user.email), edit_user_path(current_user) %>!</strong> 
          <%= link_to "Sign out", session_path("current"), method: :delete %> 
        <% else %> 
          <%= link_to "Sign Up", new_user_path %>
          <%= link_to "Sign In", new_session_path %>
        <% end %>
      </ul>
    </div>
  </div>

  <% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
    <% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= flash[:error] %>
  </div>
  <% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= flash[:alert] %>
  </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <h2>Manage User Account</h2>

  <div class="row">
    <div class="col-md-8">
      <h3>Change name, email or password</h3>
      <%= form_for current_user do |f| %>
        <% if current_user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% current_user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %> 

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
            <i>(leave blank if you don't want to change it)</i>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control', placeholder: "Enter new password" %>
            <i>(leave blank if you don't want to change it)</i>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
          </div>
          <div class="form-group">
            <%= f.label :current_password %>
            <%= f.password_field :current_password, class: 'form-control', placeholder: "Enter current password" %>
            <i>(we need your current password to confirm your changes)</i>
          </div>
          <div class="form-group">
            <%= f.submit "Update", class: 'btn btn-primary' %>
          </div>
          <% if current_user && current_user.role == 'standard' %>
            <%= link_to "Upgrade My Account to Premium", new_charge_path, class: 'btn btn-success' %>
          <% else %>
            <%= link_to "Downgrade", new_charge_path, class: 'btn btn-warning' %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2>Sign up</h2>

  <div class="row">
    <div class="col-md-8">
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %> 

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
          </div>
          <div class="form-group">
            <%= f.submit "Sign up", class: 'btn btn-primary' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="container">
  <h1>Blocipedia: A SaaS Wiki Collaboration Tool</h1>
  <p>We're building a production quality SaaS app that allows users to create their own wikis.</p>
</div>

app/views/welcome/index.html.erb
<br>
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to Blocipedia</h1>
    <p>This is the home page for Blocipedia. Become a member today to start creating your very own wikis.</p>
    <p>
      <%= link_to "Sign In", new_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
    </p>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
 <div class="form-group">
   <%= f.label :title %>
   <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
 </div>
 <div class="form-group">
   <%= f.label :body %>
   <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
 </div>
  <% if current_user.role == 'admin' || current_user.role == 'premium' %>
    <div class="form-group">
      <%= f.label :public, class: 'checkbox' do %>
      <%= f.check_box :public %> Public wiki
      <% end %>
    </div>
    <% end %> 
 <div class="form-group">
   <%= f.submit "Save", class: 'btn btn-primary' %>
 </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
 <div class="col-md-4">
   <p>Things to remember:</p>
   <ul>
    <li>Always cite your sources.</li>
    <li>No need to warn readers of spoilers.</li>
    <li>Non-free content must comply with U.S. copyright law.</li>
    <li>Plagiarism will get you banned. No exceptions.</li>
   </ul>
 </div>
 <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
 </div>
</div>

app/views/wikis/index.html.erb
<div class="container">
  <h1>All Wikis</h1>
  <div class="row">
    <div class="col-md-10">
      <% @wikis.each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to wiki.title, wiki %>
            </h4>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    
    <%= will_paginate @wikis %>
    
    <div class="pull-right">
      <div class="col-md-4">
        <% if policy(Wiki.new).create? %>
          <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
</div>

app/views/wikis/new.html.erb
<div class="container">
  <h1>Create a New Wiki</h1>

  <div class="row">
   <div class="col-md-4">
     <p>Guidelines to follow when creating new Wikis:</p>
     <ul>
      <li>Always cite your sources.</li>
      <li>No need to warn readers of spoilers.</li>
      <li>Non-free content must comply with U.S. copyright law.</li>
      <li>Plagiarism will get you banned. No exceptions.</li>
     </ul>
   </div>
   <div class="col-md-8">

    <%= render partial: 'form', locals: { wiki: @wiki } %>

   </div>
  </div>
</div>

app/views/wikis/show.html.erb
<% if policy(@wiki).show? %>
  <div class="container">
    <div class="col-md-8">
      <h1><%= markdown_to_html @wiki.title %></h1>
      <p><%= markdown_to_html @wiki.body %></p>
      </div>

      <div class="pull-right col-md-3">
        <% if policy(@wiki).edit? %>
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-primary' %>
      <% end %>

      <% if policy(@wiki).destroy? %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
      <% end %>

      <% if @wiki.public == false %>
        <h4>Wiki owner: <%= @wiki.user.name %></h4>
        <h5>Collaborators:</h5> 
        <div class='js-collaborators'>
          <%= render partial: 'collaborators/collaborator', locals: { wiki: @wiki } %>
        </div>
          <% if @wiki.user_id == current_user.id || current_user.admin? %> 
            <div class='new-collaborator'>
            <%= render partial: 'collaborators/users', locals: { wiki: @wiki } %>
            </div>
          </div>
          <% end %>
      <% end %>
    </div>
  </div>
<% end %> 